#pragma once
#define EXPORT_VAR extern
#define EXPORT_FUNC
// Standard C++ includes
#include <random>
#include <string>
#include <stdexcept>

// Standard C includes
#include <cassert>
#include <cstdint>
#define DT 1.00000000000000000e+00f
typedef float scalar;
#define SCALAR_MIN 1.175494351e-38f
#define SCALAR_MAX 3.402823466e+38f

#define TIME_MIN 1.175494351e-38f
#define TIME_MAX 3.402823466e+38f

// ------------------------------------------------------------------------
// bit tool macros
#define B(x,i) ((x) & (0x80000000 >> (i))) //!< Extract the bit at the specified position i from x
#define setB(x,i) x= ((x) | (0x80000000 >> (i))) //!< Set the bit at the specified position i in x to 1
#define delB(x,i) x= ((x) & (~(0x80000000 >> (i)))) //!< Set the bit at the specified position i in x to 0

extern "C" {
// ------------------------------------------------------------------------
// global variables
// ------------------------------------------------------------------------
EXPORT_VAR unsigned long long iT;
EXPORT_VAR float t;

// ------------------------------------------------------------------------
// timers
// ------------------------------------------------------------------------
EXPORT_VAR double initTime;
EXPORT_VAR double initSparseTime;
EXPORT_VAR double neuronUpdateTime;
EXPORT_VAR double presynapticUpdateTime;
EXPORT_VAR double postsynapticUpdateTime;
EXPORT_VAR double synapseDynamicsTime;
// ------------------------------------------------------------------------
// local neuron groups
// ------------------------------------------------------------------------
#define spikeCount_LGN glbSpkCntLGN[0]
#define spike_LGN glbSpkLGN
#define glbSpkShiftLGN 0

EXPORT_VAR unsigned int* glbSpkCntLGN;
EXPORT_VAR unsigned int* d_glbSpkCntLGN;
EXPORT_VAR unsigned int* glbSpkLGN;
EXPORT_VAR unsigned int* d_glbSpkLGN;
EXPORT_VAR scalar* rLGN;
EXPORT_VAR scalar* d_rLGN;
EXPORT_VAR scalar* inputLGN;
EXPORT_VAR scalar* d_inputLGN;
#define spikeCount_V1L23E glbSpkCntV1L23E[0]
#define spike_V1L23E glbSpkV1L23E
#define glbSpkShiftV1L23E 0

EXPORT_VAR unsigned int* glbSpkCntV1L23E;
EXPORT_VAR unsigned int* d_glbSpkCntV1L23E;
EXPORT_VAR unsigned int* glbSpkV1L23E;
EXPORT_VAR unsigned int* d_glbSpkV1L23E;
EXPORT_VAR scalar* mV1L23E;
EXPORT_VAR scalar* d_mV1L23E;
EXPORT_VAR scalar* rV1L23E;
EXPORT_VAR scalar* d_rV1L23E;
EXPORT_VAR scalar* thetaV1L23E;
EXPORT_VAR scalar* d_thetaV1L23E;
EXPORT_VAR scalar* aV1L23E;
EXPORT_VAR scalar* d_aV1L23E;
#define spikeCount_V1L23I glbSpkCntV1L23I[0]
#define spike_V1L23I glbSpkV1L23I
#define glbSpkShiftV1L23I 0

EXPORT_VAR unsigned int* glbSpkCntV1L23I;
EXPORT_VAR unsigned int* d_glbSpkCntV1L23I;
EXPORT_VAR unsigned int* glbSpkV1L23I;
EXPORT_VAR unsigned int* d_glbSpkV1L23I;
EXPORT_VAR scalar* mV1L23I;
EXPORT_VAR scalar* d_mV1L23I;
EXPORT_VAR scalar* rV1L23I;
EXPORT_VAR scalar* d_rV1L23I;
EXPORT_VAR scalar* thetaV1L23I;
EXPORT_VAR scalar* d_thetaV1L23I;
EXPORT_VAR scalar* aV1L23I;
EXPORT_VAR scalar* d_aV1L23I;
#define spikeCount_V1L4E glbSpkCntV1L4E[0]
#define spike_V1L4E glbSpkV1L4E
#define glbSpkShiftV1L4E 0

EXPORT_VAR unsigned int* glbSpkCntV1L4E;
EXPORT_VAR unsigned int* d_glbSpkCntV1L4E;
EXPORT_VAR unsigned int* glbSpkV1L4E;
EXPORT_VAR unsigned int* d_glbSpkV1L4E;
EXPORT_VAR scalar* mV1L4E;
EXPORT_VAR scalar* d_mV1L4E;
EXPORT_VAR scalar* rV1L4E;
EXPORT_VAR scalar* d_rV1L4E;
EXPORT_VAR scalar* thetaV1L4E;
EXPORT_VAR scalar* d_thetaV1L4E;
EXPORT_VAR scalar* aV1L4E;
EXPORT_VAR scalar* d_aV1L4E;
#define spikeCount_V1L4I glbSpkCntV1L4I[0]
#define spike_V1L4I glbSpkV1L4I
#define glbSpkShiftV1L4I 0

EXPORT_VAR unsigned int* glbSpkCntV1L4I;
EXPORT_VAR unsigned int* d_glbSpkCntV1L4I;
EXPORT_VAR unsigned int* glbSpkV1L4I;
EXPORT_VAR unsigned int* d_glbSpkV1L4I;
EXPORT_VAR scalar* mV1L4I;
EXPORT_VAR scalar* d_mV1L4I;
EXPORT_VAR scalar* rV1L4I;
EXPORT_VAR scalar* d_rV1L4I;
EXPORT_VAR scalar* thetaV1L4I;
EXPORT_VAR scalar* d_thetaV1L4I;
EXPORT_VAR scalar* aV1L4I;
EXPORT_VAR scalar* d_aV1L4I;
#define spikeCount_V2L23E glbSpkCntV2L23E[0]
#define spike_V2L23E glbSpkV2L23E
#define glbSpkShiftV2L23E 0

EXPORT_VAR unsigned int* glbSpkCntV2L23E;
EXPORT_VAR unsigned int* d_glbSpkCntV2L23E;
EXPORT_VAR unsigned int* glbSpkV2L23E;
EXPORT_VAR unsigned int* d_glbSpkV2L23E;
EXPORT_VAR scalar* mV2L23E;
EXPORT_VAR scalar* d_mV2L23E;
EXPORT_VAR scalar* rV2L23E;
EXPORT_VAR scalar* d_rV2L23E;
EXPORT_VAR scalar* thetaV2L23E;
EXPORT_VAR scalar* d_thetaV2L23E;
EXPORT_VAR scalar* aV2L23E;
EXPORT_VAR scalar* d_aV2L23E;
#define spikeCount_V2L23I glbSpkCntV2L23I[0]
#define spike_V2L23I glbSpkV2L23I
#define glbSpkShiftV2L23I 0

EXPORT_VAR unsigned int* glbSpkCntV2L23I;
EXPORT_VAR unsigned int* d_glbSpkCntV2L23I;
EXPORT_VAR unsigned int* glbSpkV2L23I;
EXPORT_VAR unsigned int* d_glbSpkV2L23I;
EXPORT_VAR scalar* mV2L23I;
EXPORT_VAR scalar* d_mV2L23I;
EXPORT_VAR scalar* rV2L23I;
EXPORT_VAR scalar* d_rV2L23I;
EXPORT_VAR scalar* thetaV2L23I;
EXPORT_VAR scalar* d_thetaV2L23I;
EXPORT_VAR scalar* aV2L23I;
EXPORT_VAR scalar* d_aV2L23I;
#define spikeCount_V2L4E glbSpkCntV2L4E[0]
#define spike_V2L4E glbSpkV2L4E
#define glbSpkShiftV2L4E 0

EXPORT_VAR unsigned int* glbSpkCntV2L4E;
EXPORT_VAR unsigned int* d_glbSpkCntV2L4E;
EXPORT_VAR unsigned int* glbSpkV2L4E;
EXPORT_VAR unsigned int* d_glbSpkV2L4E;
EXPORT_VAR scalar* mV2L4E;
EXPORT_VAR scalar* d_mV2L4E;
EXPORT_VAR scalar* rV2L4E;
EXPORT_VAR scalar* d_rV2L4E;
EXPORT_VAR scalar* thetaV2L4E;
EXPORT_VAR scalar* d_thetaV2L4E;
EXPORT_VAR scalar* aV2L4E;
EXPORT_VAR scalar* d_aV2L4E;
#define spikeCount_V2L4I glbSpkCntV2L4I[0]
#define spike_V2L4I glbSpkV2L4I
#define glbSpkShiftV2L4I 0

EXPORT_VAR unsigned int* glbSpkCntV2L4I;
EXPORT_VAR unsigned int* d_glbSpkCntV2L4I;
EXPORT_VAR unsigned int* glbSpkV2L4I;
EXPORT_VAR unsigned int* d_glbSpkV2L4I;
EXPORT_VAR scalar* mV2L4I;
EXPORT_VAR scalar* d_mV2L4I;
EXPORT_VAR scalar* rV2L4I;
EXPORT_VAR scalar* d_rV2L4I;
EXPORT_VAR scalar* thetaV2L4I;
EXPORT_VAR scalar* d_thetaV2L4I;
EXPORT_VAR scalar* aV2L4I;
EXPORT_VAR scalar* d_aV2L4I;

// ------------------------------------------------------------------------
// custom update variables
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// pre and postsynaptic variables
// ------------------------------------------------------------------------
EXPORT_VAR float* inSynV1L4I_V1L23E;
EXPORT_VAR float* d_inSynV1L4I_V1L23E;
EXPORT_VAR float* denDelayV1L4I_V1L23E;
EXPORT_VAR float* d_denDelayV1L4I_V1L23E;
EXPORT_VAR unsigned int denDelayPtrV1L4I_V1L23E;
EXPORT_VAR unsigned int* d_denDelayPtrV1L4I_V1L23E;
EXPORT_VAR float* inSynV2L23E_V1L23E;
EXPORT_VAR float* d_inSynV2L23E_V1L23E;
EXPORT_VAR float* denDelayV2L23E_V1L23E;
EXPORT_VAR float* d_denDelayV2L23E_V1L23E;
EXPORT_VAR unsigned int denDelayPtrV2L23E_V1L23E;
EXPORT_VAR unsigned int* d_denDelayPtrV2L23E_V1L23E;
EXPORT_VAR float* inSynV1L23I_V1L23E;
EXPORT_VAR float* d_inSynV1L23I_V1L23E;
EXPORT_VAR float* denDelayV1L23I_V1L23E;
EXPORT_VAR float* d_denDelayV1L23I_V1L23E;
EXPORT_VAR unsigned int denDelayPtrV1L23I_V1L23E;
EXPORT_VAR unsigned int* d_denDelayPtrV1L23I_V1L23E;
EXPORT_VAR float* inSynV1L4E_V1L23E;
EXPORT_VAR float* d_inSynV1L4E_V1L23E;
EXPORT_VAR float* denDelayV1L4E_V1L23E;
EXPORT_VAR float* d_denDelayV1L4E_V1L23E;
EXPORT_VAR unsigned int denDelayPtrV1L4E_V1L23E;
EXPORT_VAR unsigned int* d_denDelayPtrV1L4E_V1L23E;
EXPORT_VAR float* inSynV1L4I_V1L23I;
EXPORT_VAR float* d_inSynV1L4I_V1L23I;
EXPORT_VAR float* denDelayV1L4I_V1L23I;
EXPORT_VAR float* d_denDelayV1L4I_V1L23I;
EXPORT_VAR unsigned int denDelayPtrV1L4I_V1L23I;
EXPORT_VAR unsigned int* d_denDelayPtrV1L4I_V1L23I;
EXPORT_VAR float* inSynV2L23E_V1L23I;
EXPORT_VAR float* d_inSynV2L23E_V1L23I;
EXPORT_VAR float* denDelayV2L23E_V1L23I;
EXPORT_VAR float* d_denDelayV2L23E_V1L23I;
EXPORT_VAR unsigned int denDelayPtrV2L23E_V1L23I;
EXPORT_VAR unsigned int* d_denDelayPtrV2L23E_V1L23I;
EXPORT_VAR float* inSynV1L23I_V1L23I;
EXPORT_VAR float* d_inSynV1L23I_V1L23I;
EXPORT_VAR float* denDelayV1L23I_V1L23I;
EXPORT_VAR float* d_denDelayV1L23I_V1L23I;
EXPORT_VAR unsigned int denDelayPtrV1L23I_V1L23I;
EXPORT_VAR unsigned int* d_denDelayPtrV1L23I_V1L23I;
EXPORT_VAR float* inSynV1L23E_V1L23I;
EXPORT_VAR float* d_inSynV1L23E_V1L23I;
EXPORT_VAR float* denDelayV1L23E_V1L23I;
EXPORT_VAR float* d_denDelayV1L23E_V1L23I;
EXPORT_VAR unsigned int denDelayPtrV1L23E_V1L23I;
EXPORT_VAR unsigned int* d_denDelayPtrV1L23E_V1L23I;
EXPORT_VAR float* inSynV1L4E_V1L23I;
EXPORT_VAR float* d_inSynV1L4E_V1L23I;
EXPORT_VAR float* denDelayV1L4E_V1L23I;
EXPORT_VAR float* d_denDelayV1L4E_V1L23I;
EXPORT_VAR unsigned int denDelayPtrV1L4E_V1L23I;
EXPORT_VAR unsigned int* d_denDelayPtrV1L4E_V1L23I;
EXPORT_VAR float* inSynV1L4I_V1L4E;
EXPORT_VAR float* d_inSynV1L4I_V1L4E;
EXPORT_VAR float* denDelayV1L4I_V1L4E;
EXPORT_VAR float* d_denDelayV1L4I_V1L4E;
EXPORT_VAR unsigned int denDelayPtrV1L4I_V1L4E;
EXPORT_VAR unsigned int* d_denDelayPtrV1L4I_V1L4E;
EXPORT_VAR float* inSynLGN_V1L4E;
EXPORT_VAR float* d_inSynLGN_V1L4E;
EXPORT_VAR float* denDelayLGN_V1L4E;
EXPORT_VAR float* d_denDelayLGN_V1L4E;
EXPORT_VAR unsigned int denDelayPtrLGN_V1L4E;
EXPORT_VAR unsigned int* d_denDelayPtrLGN_V1L4E;
EXPORT_VAR float* inSynV1L23E_V1L4I;
EXPORT_VAR float* d_inSynV1L23E_V1L4I;
EXPORT_VAR float* denDelayV1L23E_V1L4I;
EXPORT_VAR float* d_denDelayV1L23E_V1L4I;
EXPORT_VAR unsigned int denDelayPtrV1L23E_V1L4I;
EXPORT_VAR unsigned int* d_denDelayPtrV1L23E_V1L4I;
EXPORT_VAR float* inSynV1L4I_V1L4I;
EXPORT_VAR float* d_inSynV1L4I_V1L4I;
EXPORT_VAR float* denDelayV1L4I_V1L4I;
EXPORT_VAR float* d_denDelayV1L4I_V1L4I;
EXPORT_VAR unsigned int denDelayPtrV1L4I_V1L4I;
EXPORT_VAR unsigned int* d_denDelayPtrV1L4I_V1L4I;
EXPORT_VAR float* inSynV1L4E_V1L4I;
EXPORT_VAR float* d_inSynV1L4E_V1L4I;
EXPORT_VAR float* denDelayV1L4E_V1L4I;
EXPORT_VAR float* d_denDelayV1L4E_V1L4I;
EXPORT_VAR unsigned int denDelayPtrV1L4E_V1L4I;
EXPORT_VAR unsigned int* d_denDelayPtrV1L4E_V1L4I;
EXPORT_VAR float* inSynLGN_V1L4I;
EXPORT_VAR float* d_inSynLGN_V1L4I;
EXPORT_VAR float* denDelayLGN_V1L4I;
EXPORT_VAR float* d_denDelayLGN_V1L4I;
EXPORT_VAR unsigned int denDelayPtrLGN_V1L4I;
EXPORT_VAR unsigned int* d_denDelayPtrLGN_V1L4I;
EXPORT_VAR float* inSynV2L4I_V2L23E;
EXPORT_VAR float* d_inSynV2L4I_V2L23E;
EXPORT_VAR float* denDelayV2L4I_V2L23E;
EXPORT_VAR float* d_denDelayV2L4I_V2L23E;
EXPORT_VAR unsigned int denDelayPtrV2L4I_V2L23E;
EXPORT_VAR unsigned int* d_denDelayPtrV2L4I_V2L23E;
EXPORT_VAR float* inSynV2L23I_V2L23E;
EXPORT_VAR float* d_inSynV2L23I_V2L23E;
EXPORT_VAR float* denDelayV2L23I_V2L23E;
EXPORT_VAR float* d_denDelayV2L23I_V2L23E;
EXPORT_VAR unsigned int denDelayPtrV2L23I_V2L23E;
EXPORT_VAR unsigned int* d_denDelayPtrV2L23I_V2L23E;
EXPORT_VAR float* inSynV2L4E_V2L23E;
EXPORT_VAR float* d_inSynV2L4E_V2L23E;
EXPORT_VAR float* denDelayV2L4E_V2L23E;
EXPORT_VAR float* d_denDelayV2L4E_V2L23E;
EXPORT_VAR unsigned int denDelayPtrV2L4E_V2L23E;
EXPORT_VAR unsigned int* d_denDelayPtrV2L4E_V2L23E;
EXPORT_VAR float* inSynV2L4I_V2L23I;
EXPORT_VAR float* d_inSynV2L4I_V2L23I;
EXPORT_VAR float* denDelayV2L4I_V2L23I;
EXPORT_VAR float* d_denDelayV2L4I_V2L23I;
EXPORT_VAR unsigned int denDelayPtrV2L4I_V2L23I;
EXPORT_VAR unsigned int* d_denDelayPtrV2L4I_V2L23I;
EXPORT_VAR float* inSynV2L23I_V2L23I;
EXPORT_VAR float* d_inSynV2L23I_V2L23I;
EXPORT_VAR float* denDelayV2L23I_V2L23I;
EXPORT_VAR float* d_denDelayV2L23I_V2L23I;
EXPORT_VAR unsigned int denDelayPtrV2L23I_V2L23I;
EXPORT_VAR unsigned int* d_denDelayPtrV2L23I_V2L23I;
EXPORT_VAR float* inSynV2L23E_V2L23I;
EXPORT_VAR float* d_inSynV2L23E_V2L23I;
EXPORT_VAR float* denDelayV2L23E_V2L23I;
EXPORT_VAR float* d_denDelayV2L23E_V2L23I;
EXPORT_VAR unsigned int denDelayPtrV2L23E_V2L23I;
EXPORT_VAR unsigned int* d_denDelayPtrV2L23E_V2L23I;
EXPORT_VAR float* inSynV2L4E_V2L23I;
EXPORT_VAR float* d_inSynV2L4E_V2L23I;
EXPORT_VAR float* denDelayV2L4E_V2L23I;
EXPORT_VAR float* d_denDelayV2L4E_V2L23I;
EXPORT_VAR unsigned int denDelayPtrV2L4E_V2L23I;
EXPORT_VAR unsigned int* d_denDelayPtrV2L4E_V2L23I;
EXPORT_VAR float* inSynV2L4I_V2L4E;
EXPORT_VAR float* d_inSynV2L4I_V2L4E;
EXPORT_VAR float* denDelayV2L4I_V2L4E;
EXPORT_VAR float* d_denDelayV2L4I_V2L4E;
EXPORT_VAR unsigned int denDelayPtrV2L4I_V2L4E;
EXPORT_VAR unsigned int* d_denDelayPtrV2L4I_V2L4E;
EXPORT_VAR float* inSynV1L23E_V2L4E;
EXPORT_VAR float* d_inSynV1L23E_V2L4E;
EXPORT_VAR float* denDelayV1L23E_V2L4E;
EXPORT_VAR float* d_denDelayV1L23E_V2L4E;
EXPORT_VAR unsigned int denDelayPtrV1L23E_V2L4E;
EXPORT_VAR unsigned int* d_denDelayPtrV1L23E_V2L4E;
EXPORT_VAR float* inSynV2L23E_V2L4I;
EXPORT_VAR float* d_inSynV2L23E_V2L4I;
EXPORT_VAR float* denDelayV2L23E_V2L4I;
EXPORT_VAR float* d_denDelayV2L23E_V2L4I;
EXPORT_VAR unsigned int denDelayPtrV2L23E_V2L4I;
EXPORT_VAR unsigned int* d_denDelayPtrV2L23E_V2L4I;
EXPORT_VAR float* inSynV2L4I_V2L4I;
EXPORT_VAR float* d_inSynV2L4I_V2L4I;
EXPORT_VAR float* denDelayV2L4I_V2L4I;
EXPORT_VAR float* d_denDelayV2L4I_V2L4I;
EXPORT_VAR unsigned int denDelayPtrV2L4I_V2L4I;
EXPORT_VAR unsigned int* d_denDelayPtrV2L4I_V2L4I;
EXPORT_VAR float* inSynV2L4E_V2L4I;
EXPORT_VAR float* d_inSynV2L4E_V2L4I;
EXPORT_VAR float* denDelayV2L4E_V2L4I;
EXPORT_VAR float* d_denDelayV2L4E_V2L4I;
EXPORT_VAR unsigned int denDelayPtrV2L4E_V2L4I;
EXPORT_VAR unsigned int* d_denDelayPtrV2L4E_V2L4I;
EXPORT_VAR float* inSynV1L23E_V2L4I;
EXPORT_VAR float* d_inSynV1L23E_V2L4I;
EXPORT_VAR float* denDelayV1L23E_V2L4I;
EXPORT_VAR float* d_denDelayV1L23E_V2L4I;
EXPORT_VAR unsigned int denDelayPtrV1L23E_V2L4I;
EXPORT_VAR unsigned int* d_denDelayPtrV1L23E_V2L4I;

// ------------------------------------------------------------------------
// synapse connectivity
// ------------------------------------------------------------------------

// ------------------------------------------------------------------------
// synapse variables
// ------------------------------------------------------------------------
EXPORT_VAR scalar* wLGN_V1L4E;
EXPORT_VAR scalar* d_wLGN_V1L4E;
EXPORT_VAR bool* activeLGN_V1L4E;
EXPORT_VAR bool* d_activeLGN_V1L4E;
EXPORT_VAR uint8_t* delayLGN_V1L4E;
EXPORT_VAR uint8_t* d_delayLGN_V1L4E;
EXPORT_VAR scalar* wLGN_V1L4I;
EXPORT_VAR scalar* d_wLGN_V1L4I;
EXPORT_VAR bool* activeLGN_V1L4I;
EXPORT_VAR bool* d_activeLGN_V1L4I;
EXPORT_VAR uint8_t* delayLGN_V1L4I;
EXPORT_VAR uint8_t* d_delayLGN_V1L4I;
EXPORT_VAR scalar* wV1L23E_V1L23I;
EXPORT_VAR scalar* d_wV1L23E_V1L23I;
EXPORT_VAR bool* activeV1L23E_V1L23I;
EXPORT_VAR bool* d_activeV1L23E_V1L23I;
EXPORT_VAR uint8_t* delayV1L23E_V1L23I;
EXPORT_VAR uint8_t* d_delayV1L23E_V1L23I;
EXPORT_VAR scalar* wV1L23E_V1L4I;
EXPORT_VAR scalar* d_wV1L23E_V1L4I;
EXPORT_VAR bool* activeV1L23E_V1L4I;
EXPORT_VAR bool* d_activeV1L23E_V1L4I;
EXPORT_VAR uint8_t* delayV1L23E_V1L4I;
EXPORT_VAR uint8_t* d_delayV1L23E_V1L4I;
EXPORT_VAR scalar* wV1L23E_V2L4E;
EXPORT_VAR scalar* d_wV1L23E_V2L4E;
EXPORT_VAR bool* activeV1L23E_V2L4E;
EXPORT_VAR bool* d_activeV1L23E_V2L4E;
EXPORT_VAR uint8_t* delayV1L23E_V2L4E;
EXPORT_VAR uint8_t* d_delayV1L23E_V2L4E;
EXPORT_VAR scalar* wV1L23E_V2L4I;
EXPORT_VAR scalar* d_wV1L23E_V2L4I;
EXPORT_VAR bool* activeV1L23E_V2L4I;
EXPORT_VAR bool* d_activeV1L23E_V2L4I;
EXPORT_VAR uint8_t* delayV1L23E_V2L4I;
EXPORT_VAR uint8_t* d_delayV1L23E_V2L4I;
EXPORT_VAR scalar* wV1L23I_V1L23E;
EXPORT_VAR scalar* d_wV1L23I_V1L23E;
EXPORT_VAR bool* activeV1L23I_V1L23E;
EXPORT_VAR bool* d_activeV1L23I_V1L23E;
EXPORT_VAR uint8_t* delayV1L23I_V1L23E;
EXPORT_VAR uint8_t* d_delayV1L23I_V1L23E;
EXPORT_VAR scalar* wV1L23I_V1L23I;
EXPORT_VAR scalar* d_wV1L23I_V1L23I;
EXPORT_VAR bool* activeV1L23I_V1L23I;
EXPORT_VAR bool* d_activeV1L23I_V1L23I;
EXPORT_VAR uint8_t* delayV1L23I_V1L23I;
EXPORT_VAR uint8_t* d_delayV1L23I_V1L23I;
EXPORT_VAR scalar* wV1L4E_V1L23E;
EXPORT_VAR scalar* d_wV1L4E_V1L23E;
EXPORT_VAR bool* activeV1L4E_V1L23E;
EXPORT_VAR bool* d_activeV1L4E_V1L23E;
EXPORT_VAR uint8_t* delayV1L4E_V1L23E;
EXPORT_VAR uint8_t* d_delayV1L4E_V1L23E;
EXPORT_VAR scalar* wV1L4E_V1L23I;
EXPORT_VAR scalar* d_wV1L4E_V1L23I;
EXPORT_VAR bool* activeV1L4E_V1L23I;
EXPORT_VAR bool* d_activeV1L4E_V1L23I;
EXPORT_VAR uint8_t* delayV1L4E_V1L23I;
EXPORT_VAR uint8_t* d_delayV1L4E_V1L23I;
EXPORT_VAR scalar* wV1L4E_V1L4I;
EXPORT_VAR scalar* d_wV1L4E_V1L4I;
EXPORT_VAR bool* activeV1L4E_V1L4I;
EXPORT_VAR bool* d_activeV1L4E_V1L4I;
EXPORT_VAR uint8_t* delayV1L4E_V1L4I;
EXPORT_VAR uint8_t* d_delayV1L4E_V1L4I;
EXPORT_VAR scalar* wV1L4I_V1L23E;
EXPORT_VAR scalar* d_wV1L4I_V1L23E;
EXPORT_VAR bool* activeV1L4I_V1L23E;
EXPORT_VAR bool* d_activeV1L4I_V1L23E;
EXPORT_VAR uint8_t* delayV1L4I_V1L23E;
EXPORT_VAR uint8_t* d_delayV1L4I_V1L23E;
EXPORT_VAR scalar* wV1L4I_V1L23I;
EXPORT_VAR scalar* d_wV1L4I_V1L23I;
EXPORT_VAR bool* activeV1L4I_V1L23I;
EXPORT_VAR bool* d_activeV1L4I_V1L23I;
EXPORT_VAR uint8_t* delayV1L4I_V1L23I;
EXPORT_VAR uint8_t* d_delayV1L4I_V1L23I;
EXPORT_VAR scalar* wV1L4I_V1L4E;
EXPORT_VAR scalar* d_wV1L4I_V1L4E;
EXPORT_VAR bool* activeV1L4I_V1L4E;
EXPORT_VAR bool* d_activeV1L4I_V1L4E;
EXPORT_VAR uint8_t* delayV1L4I_V1L4E;
EXPORT_VAR uint8_t* d_delayV1L4I_V1L4E;
EXPORT_VAR scalar* wV1L4I_V1L4I;
EXPORT_VAR scalar* d_wV1L4I_V1L4I;
EXPORT_VAR bool* activeV1L4I_V1L4I;
EXPORT_VAR bool* d_activeV1L4I_V1L4I;
EXPORT_VAR uint8_t* delayV1L4I_V1L4I;
EXPORT_VAR uint8_t* d_delayV1L4I_V1L4I;
EXPORT_VAR scalar* wV2L23E_V1L23E;
EXPORT_VAR scalar* d_wV2L23E_V1L23E;
EXPORT_VAR bool* activeV2L23E_V1L23E;
EXPORT_VAR bool* d_activeV2L23E_V1L23E;
EXPORT_VAR uint8_t* delayV2L23E_V1L23E;
EXPORT_VAR uint8_t* d_delayV2L23E_V1L23E;
EXPORT_VAR scalar* wV2L23E_V1L23I;
EXPORT_VAR scalar* d_wV2L23E_V1L23I;
EXPORT_VAR bool* activeV2L23E_V1L23I;
EXPORT_VAR bool* d_activeV2L23E_V1L23I;
EXPORT_VAR uint8_t* delayV2L23E_V1L23I;
EXPORT_VAR uint8_t* d_delayV2L23E_V1L23I;
EXPORT_VAR scalar* wV2L23E_V2L23I;
EXPORT_VAR scalar* d_wV2L23E_V2L23I;
EXPORT_VAR bool* activeV2L23E_V2L23I;
EXPORT_VAR bool* d_activeV2L23E_V2L23I;
EXPORT_VAR uint8_t* delayV2L23E_V2L23I;
EXPORT_VAR uint8_t* d_delayV2L23E_V2L23I;
EXPORT_VAR scalar* wV2L23E_V2L4I;
EXPORT_VAR scalar* d_wV2L23E_V2L4I;
EXPORT_VAR bool* activeV2L23E_V2L4I;
EXPORT_VAR bool* d_activeV2L23E_V2L4I;
EXPORT_VAR uint8_t* delayV2L23E_V2L4I;
EXPORT_VAR uint8_t* d_delayV2L23E_V2L4I;
EXPORT_VAR scalar* wV2L23I_V2L23E;
EXPORT_VAR scalar* d_wV2L23I_V2L23E;
EXPORT_VAR bool* activeV2L23I_V2L23E;
EXPORT_VAR bool* d_activeV2L23I_V2L23E;
EXPORT_VAR uint8_t* delayV2L23I_V2L23E;
EXPORT_VAR uint8_t* d_delayV2L23I_V2L23E;
EXPORT_VAR scalar* wV2L23I_V2L23I;
EXPORT_VAR scalar* d_wV2L23I_V2L23I;
EXPORT_VAR bool* activeV2L23I_V2L23I;
EXPORT_VAR bool* d_activeV2L23I_V2L23I;
EXPORT_VAR uint8_t* delayV2L23I_V2L23I;
EXPORT_VAR uint8_t* d_delayV2L23I_V2L23I;
EXPORT_VAR scalar* wV2L4E_V2L23E;
EXPORT_VAR scalar* d_wV2L4E_V2L23E;
EXPORT_VAR bool* activeV2L4E_V2L23E;
EXPORT_VAR bool* d_activeV2L4E_V2L23E;
EXPORT_VAR uint8_t* delayV2L4E_V2L23E;
EXPORT_VAR uint8_t* d_delayV2L4E_V2L23E;
EXPORT_VAR scalar* wV2L4E_V2L23I;
EXPORT_VAR scalar* d_wV2L4E_V2L23I;
EXPORT_VAR bool* activeV2L4E_V2L23I;
EXPORT_VAR bool* d_activeV2L4E_V2L23I;
EXPORT_VAR uint8_t* delayV2L4E_V2L23I;
EXPORT_VAR uint8_t* d_delayV2L4E_V2L23I;
EXPORT_VAR scalar* wV2L4E_V2L4I;
EXPORT_VAR scalar* d_wV2L4E_V2L4I;
EXPORT_VAR bool* activeV2L4E_V2L4I;
EXPORT_VAR bool* d_activeV2L4E_V2L4I;
EXPORT_VAR uint8_t* delayV2L4E_V2L4I;
EXPORT_VAR uint8_t* d_delayV2L4E_V2L4I;
EXPORT_VAR scalar* wV2L4I_V2L23E;
EXPORT_VAR scalar* d_wV2L4I_V2L23E;
EXPORT_VAR bool* activeV2L4I_V2L23E;
EXPORT_VAR bool* d_activeV2L4I_V2L23E;
EXPORT_VAR uint8_t* delayV2L4I_V2L23E;
EXPORT_VAR uint8_t* d_delayV2L4I_V2L23E;
EXPORT_VAR scalar* wV2L4I_V2L23I;
EXPORT_VAR scalar* d_wV2L4I_V2L23I;
EXPORT_VAR bool* activeV2L4I_V2L23I;
EXPORT_VAR bool* d_activeV2L4I_V2L23I;
EXPORT_VAR uint8_t* delayV2L4I_V2L23I;
EXPORT_VAR uint8_t* d_delayV2L4I_V2L23I;
EXPORT_VAR scalar* wV2L4I_V2L4E;
EXPORT_VAR scalar* d_wV2L4I_V2L4E;
EXPORT_VAR bool* activeV2L4I_V2L4E;
EXPORT_VAR bool* d_activeV2L4I_V2L4E;
EXPORT_VAR uint8_t* delayV2L4I_V2L4E;
EXPORT_VAR uint8_t* d_delayV2L4I_V2L4E;
EXPORT_VAR scalar* wV2L4I_V2L4I;
EXPORT_VAR scalar* d_wV2L4I_V2L4I;
EXPORT_VAR bool* activeV2L4I_V2L4I;
EXPORT_VAR bool* d_activeV2L4I_V2L4I;
EXPORT_VAR uint8_t* delayV2L4I_V2L4I;
EXPORT_VAR uint8_t* d_delayV2L4I_V2L4I;

EXPORT_FUNC void pushLGNSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullLGNSpikesFromDevice();
EXPORT_FUNC void pushLGNCurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullLGNCurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getLGNCurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getLGNCurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushrLGNToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrLGNFromDevice();
EXPORT_FUNC void pushCurrentrLGNToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrLGNFromDevice();
EXPORT_FUNC scalar* getCurrentrLGN(unsigned int batch = 0); 
EXPORT_FUNC void pushinputLGNToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinputLGNFromDevice();
EXPORT_FUNC void pushCurrentinputLGNToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentinputLGNFromDevice();
EXPORT_FUNC scalar* getCurrentinputLGN(unsigned int batch = 0); 
EXPORT_FUNC void pushLGNStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullLGNStateFromDevice();
EXPORT_FUNC void pushV1L23ESpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23ESpikesFromDevice();
EXPORT_FUNC void pushV1L23ECurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23ECurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getV1L23ECurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getV1L23ECurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushmV1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullmV1L23EFromDevice();
EXPORT_FUNC void pushCurrentmV1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentmV1L23EFromDevice();
EXPORT_FUNC scalar* getCurrentmV1L23E(unsigned int batch = 0); 
EXPORT_FUNC void pushrV1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrV1L23EFromDevice();
EXPORT_FUNC void pushCurrentrV1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrV1L23EFromDevice();
EXPORT_FUNC scalar* getCurrentrV1L23E(unsigned int batch = 0); 
EXPORT_FUNC void pushthetaV1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullthetaV1L23EFromDevice();
EXPORT_FUNC void pushCurrentthetaV1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentthetaV1L23EFromDevice();
EXPORT_FUNC scalar* getCurrentthetaV1L23E(unsigned int batch = 0); 
EXPORT_FUNC void pushaV1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullaV1L23EFromDevice();
EXPORT_FUNC void pushCurrentaV1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentaV1L23EFromDevice();
EXPORT_FUNC scalar* getCurrentaV1L23E(unsigned int batch = 0); 
EXPORT_FUNC void pushV1L23EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23EStateFromDevice();
EXPORT_FUNC void pushV1L23ISpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23ISpikesFromDevice();
EXPORT_FUNC void pushV1L23ICurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23ICurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getV1L23ICurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getV1L23ICurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushmV1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullmV1L23IFromDevice();
EXPORT_FUNC void pushCurrentmV1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentmV1L23IFromDevice();
EXPORT_FUNC scalar* getCurrentmV1L23I(unsigned int batch = 0); 
EXPORT_FUNC void pushrV1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrV1L23IFromDevice();
EXPORT_FUNC void pushCurrentrV1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrV1L23IFromDevice();
EXPORT_FUNC scalar* getCurrentrV1L23I(unsigned int batch = 0); 
EXPORT_FUNC void pushthetaV1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullthetaV1L23IFromDevice();
EXPORT_FUNC void pushCurrentthetaV1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentthetaV1L23IFromDevice();
EXPORT_FUNC scalar* getCurrentthetaV1L23I(unsigned int batch = 0); 
EXPORT_FUNC void pushaV1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullaV1L23IFromDevice();
EXPORT_FUNC void pushCurrentaV1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentaV1L23IFromDevice();
EXPORT_FUNC scalar* getCurrentaV1L23I(unsigned int batch = 0); 
EXPORT_FUNC void pushV1L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23IStateFromDevice();
EXPORT_FUNC void pushV1L4ESpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4ESpikesFromDevice();
EXPORT_FUNC void pushV1L4ECurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4ECurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getV1L4ECurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getV1L4ECurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushmV1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullmV1L4EFromDevice();
EXPORT_FUNC void pushCurrentmV1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentmV1L4EFromDevice();
EXPORT_FUNC scalar* getCurrentmV1L4E(unsigned int batch = 0); 
EXPORT_FUNC void pushrV1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrV1L4EFromDevice();
EXPORT_FUNC void pushCurrentrV1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrV1L4EFromDevice();
EXPORT_FUNC scalar* getCurrentrV1L4E(unsigned int batch = 0); 
EXPORT_FUNC void pushthetaV1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullthetaV1L4EFromDevice();
EXPORT_FUNC void pushCurrentthetaV1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentthetaV1L4EFromDevice();
EXPORT_FUNC scalar* getCurrentthetaV1L4E(unsigned int batch = 0); 
EXPORT_FUNC void pushaV1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullaV1L4EFromDevice();
EXPORT_FUNC void pushCurrentaV1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentaV1L4EFromDevice();
EXPORT_FUNC scalar* getCurrentaV1L4E(unsigned int batch = 0); 
EXPORT_FUNC void pushV1L4EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4EStateFromDevice();
EXPORT_FUNC void pushV1L4ISpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4ISpikesFromDevice();
EXPORT_FUNC void pushV1L4ICurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4ICurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getV1L4ICurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getV1L4ICurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushmV1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullmV1L4IFromDevice();
EXPORT_FUNC void pushCurrentmV1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentmV1L4IFromDevice();
EXPORT_FUNC scalar* getCurrentmV1L4I(unsigned int batch = 0); 
EXPORT_FUNC void pushrV1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrV1L4IFromDevice();
EXPORT_FUNC void pushCurrentrV1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrV1L4IFromDevice();
EXPORT_FUNC scalar* getCurrentrV1L4I(unsigned int batch = 0); 
EXPORT_FUNC void pushthetaV1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullthetaV1L4IFromDevice();
EXPORT_FUNC void pushCurrentthetaV1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentthetaV1L4IFromDevice();
EXPORT_FUNC scalar* getCurrentthetaV1L4I(unsigned int batch = 0); 
EXPORT_FUNC void pushaV1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullaV1L4IFromDevice();
EXPORT_FUNC void pushCurrentaV1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentaV1L4IFromDevice();
EXPORT_FUNC scalar* getCurrentaV1L4I(unsigned int batch = 0); 
EXPORT_FUNC void pushV1L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4IStateFromDevice();
EXPORT_FUNC void pushV2L23ESpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23ESpikesFromDevice();
EXPORT_FUNC void pushV2L23ECurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23ECurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getV2L23ECurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getV2L23ECurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushmV2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullmV2L23EFromDevice();
EXPORT_FUNC void pushCurrentmV2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentmV2L23EFromDevice();
EXPORT_FUNC scalar* getCurrentmV2L23E(unsigned int batch = 0); 
EXPORT_FUNC void pushrV2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrV2L23EFromDevice();
EXPORT_FUNC void pushCurrentrV2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrV2L23EFromDevice();
EXPORT_FUNC scalar* getCurrentrV2L23E(unsigned int batch = 0); 
EXPORT_FUNC void pushthetaV2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullthetaV2L23EFromDevice();
EXPORT_FUNC void pushCurrentthetaV2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentthetaV2L23EFromDevice();
EXPORT_FUNC scalar* getCurrentthetaV2L23E(unsigned int batch = 0); 
EXPORT_FUNC void pushaV2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullaV2L23EFromDevice();
EXPORT_FUNC void pushCurrentaV2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentaV2L23EFromDevice();
EXPORT_FUNC scalar* getCurrentaV2L23E(unsigned int batch = 0); 
EXPORT_FUNC void pushV2L23EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23EStateFromDevice();
EXPORT_FUNC void pushV2L23ISpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23ISpikesFromDevice();
EXPORT_FUNC void pushV2L23ICurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23ICurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getV2L23ICurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getV2L23ICurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushmV2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullmV2L23IFromDevice();
EXPORT_FUNC void pushCurrentmV2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentmV2L23IFromDevice();
EXPORT_FUNC scalar* getCurrentmV2L23I(unsigned int batch = 0); 
EXPORT_FUNC void pushrV2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrV2L23IFromDevice();
EXPORT_FUNC void pushCurrentrV2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrV2L23IFromDevice();
EXPORT_FUNC scalar* getCurrentrV2L23I(unsigned int batch = 0); 
EXPORT_FUNC void pushthetaV2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullthetaV2L23IFromDevice();
EXPORT_FUNC void pushCurrentthetaV2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentthetaV2L23IFromDevice();
EXPORT_FUNC scalar* getCurrentthetaV2L23I(unsigned int batch = 0); 
EXPORT_FUNC void pushaV2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullaV2L23IFromDevice();
EXPORT_FUNC void pushCurrentaV2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentaV2L23IFromDevice();
EXPORT_FUNC scalar* getCurrentaV2L23I(unsigned int batch = 0); 
EXPORT_FUNC void pushV2L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23IStateFromDevice();
EXPORT_FUNC void pushV2L4ESpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4ESpikesFromDevice();
EXPORT_FUNC void pushV2L4ECurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4ECurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getV2L4ECurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getV2L4ECurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushmV2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullmV2L4EFromDevice();
EXPORT_FUNC void pushCurrentmV2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentmV2L4EFromDevice();
EXPORT_FUNC scalar* getCurrentmV2L4E(unsigned int batch = 0); 
EXPORT_FUNC void pushrV2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrV2L4EFromDevice();
EXPORT_FUNC void pushCurrentrV2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrV2L4EFromDevice();
EXPORT_FUNC scalar* getCurrentrV2L4E(unsigned int batch = 0); 
EXPORT_FUNC void pushthetaV2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullthetaV2L4EFromDevice();
EXPORT_FUNC void pushCurrentthetaV2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentthetaV2L4EFromDevice();
EXPORT_FUNC scalar* getCurrentthetaV2L4E(unsigned int batch = 0); 
EXPORT_FUNC void pushaV2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullaV2L4EFromDevice();
EXPORT_FUNC void pushCurrentaV2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentaV2L4EFromDevice();
EXPORT_FUNC scalar* getCurrentaV2L4E(unsigned int batch = 0); 
EXPORT_FUNC void pushV2L4EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4EStateFromDevice();
EXPORT_FUNC void pushV2L4ISpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4ISpikesFromDevice();
EXPORT_FUNC void pushV2L4ICurrentSpikesToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4ICurrentSpikesFromDevice();
EXPORT_FUNC unsigned int* getV2L4ICurrentSpikes(unsigned int batch = 0); 
EXPORT_FUNC unsigned int& getV2L4ICurrentSpikeCount(unsigned int batch = 0); 
EXPORT_FUNC void pushmV2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullmV2L4IFromDevice();
EXPORT_FUNC void pushCurrentmV2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentmV2L4IFromDevice();
EXPORT_FUNC scalar* getCurrentmV2L4I(unsigned int batch = 0); 
EXPORT_FUNC void pushrV2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullrV2L4IFromDevice();
EXPORT_FUNC void pushCurrentrV2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentrV2L4IFromDevice();
EXPORT_FUNC scalar* getCurrentrV2L4I(unsigned int batch = 0); 
EXPORT_FUNC void pushthetaV2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullthetaV2L4IFromDevice();
EXPORT_FUNC void pushCurrentthetaV2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentthetaV2L4IFromDevice();
EXPORT_FUNC scalar* getCurrentthetaV2L4I(unsigned int batch = 0); 
EXPORT_FUNC void pushaV2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullaV2L4IFromDevice();
EXPORT_FUNC void pushCurrentaV2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullCurrentaV2L4IFromDevice();
EXPORT_FUNC scalar* getCurrentaV2L4I(unsigned int batch = 0); 
EXPORT_FUNC void pushV2L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4IStateFromDevice();
EXPORT_FUNC void pushwLGN_V1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwLGN_V1L4EFromDevice();
EXPORT_FUNC void pushactiveLGN_V1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveLGN_V1L4EFromDevice();
EXPORT_FUNC void pushdelayLGN_V1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayLGN_V1L4EFromDevice();
EXPORT_FUNC void pushinSynLGN_V1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynLGN_V1L4EFromDevice();
EXPORT_FUNC void pushLGN_V1L4EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullLGN_V1L4EStateFromDevice();
EXPORT_FUNC void pushwLGN_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwLGN_V1L4IFromDevice();
EXPORT_FUNC void pushactiveLGN_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveLGN_V1L4IFromDevice();
EXPORT_FUNC void pushdelayLGN_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayLGN_V1L4IFromDevice();
EXPORT_FUNC void pushinSynLGN_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynLGN_V1L4IFromDevice();
EXPORT_FUNC void pushLGN_V1L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullLGN_V1L4IStateFromDevice();
EXPORT_FUNC void pushwV1L23E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L23E_V1L23IFromDevice();
EXPORT_FUNC void pushactiveV1L23E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L23E_V1L23IFromDevice();
EXPORT_FUNC void pushdelayV1L23E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L23E_V1L23IFromDevice();
EXPORT_FUNC void pushinSynV1L23E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L23E_V1L23IFromDevice();
EXPORT_FUNC void pushV1L23E_V1L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23E_V1L23IStateFromDevice();
EXPORT_FUNC void pushwV1L23E_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L23E_V1L4IFromDevice();
EXPORT_FUNC void pushactiveV1L23E_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L23E_V1L4IFromDevice();
EXPORT_FUNC void pushdelayV1L23E_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L23E_V1L4IFromDevice();
EXPORT_FUNC void pushinSynV1L23E_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L23E_V1L4IFromDevice();
EXPORT_FUNC void pushV1L23E_V1L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23E_V1L4IStateFromDevice();
EXPORT_FUNC void pushwV1L23E_V2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L23E_V2L4EFromDevice();
EXPORT_FUNC void pushactiveV1L23E_V2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L23E_V2L4EFromDevice();
EXPORT_FUNC void pushdelayV1L23E_V2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L23E_V2L4EFromDevice();
EXPORT_FUNC void pushinSynV1L23E_V2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L23E_V2L4EFromDevice();
EXPORT_FUNC void pushV1L23E_V2L4EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23E_V2L4EStateFromDevice();
EXPORT_FUNC void pushwV1L23E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L23E_V2L4IFromDevice();
EXPORT_FUNC void pushactiveV1L23E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L23E_V2L4IFromDevice();
EXPORT_FUNC void pushdelayV1L23E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L23E_V2L4IFromDevice();
EXPORT_FUNC void pushinSynV1L23E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L23E_V2L4IFromDevice();
EXPORT_FUNC void pushV1L23E_V2L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23E_V2L4IStateFromDevice();
EXPORT_FUNC void pushwV1L23I_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L23I_V1L23EFromDevice();
EXPORT_FUNC void pushactiveV1L23I_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L23I_V1L23EFromDevice();
EXPORT_FUNC void pushdelayV1L23I_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L23I_V1L23EFromDevice();
EXPORT_FUNC void pushinSynV1L23I_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L23I_V1L23EFromDevice();
EXPORT_FUNC void pushV1L23I_V1L23EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23I_V1L23EStateFromDevice();
EXPORT_FUNC void pushwV1L23I_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L23I_V1L23IFromDevice();
EXPORT_FUNC void pushactiveV1L23I_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L23I_V1L23IFromDevice();
EXPORT_FUNC void pushdelayV1L23I_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L23I_V1L23IFromDevice();
EXPORT_FUNC void pushinSynV1L23I_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L23I_V1L23IFromDevice();
EXPORT_FUNC void pushV1L23I_V1L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L23I_V1L23IStateFromDevice();
EXPORT_FUNC void pushwV1L4E_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L4E_V1L23EFromDevice();
EXPORT_FUNC void pushactiveV1L4E_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L4E_V1L23EFromDevice();
EXPORT_FUNC void pushdelayV1L4E_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L4E_V1L23EFromDevice();
EXPORT_FUNC void pushinSynV1L4E_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L4E_V1L23EFromDevice();
EXPORT_FUNC void pushV1L4E_V1L23EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4E_V1L23EStateFromDevice();
EXPORT_FUNC void pushwV1L4E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L4E_V1L23IFromDevice();
EXPORT_FUNC void pushactiveV1L4E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L4E_V1L23IFromDevice();
EXPORT_FUNC void pushdelayV1L4E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L4E_V1L23IFromDevice();
EXPORT_FUNC void pushinSynV1L4E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L4E_V1L23IFromDevice();
EXPORT_FUNC void pushV1L4E_V1L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4E_V1L23IStateFromDevice();
EXPORT_FUNC void pushwV1L4E_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L4E_V1L4IFromDevice();
EXPORT_FUNC void pushactiveV1L4E_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L4E_V1L4IFromDevice();
EXPORT_FUNC void pushdelayV1L4E_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L4E_V1L4IFromDevice();
EXPORT_FUNC void pushinSynV1L4E_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L4E_V1L4IFromDevice();
EXPORT_FUNC void pushV1L4E_V1L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4E_V1L4IStateFromDevice();
EXPORT_FUNC void pushwV1L4I_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L4I_V1L23EFromDevice();
EXPORT_FUNC void pushactiveV1L4I_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L4I_V1L23EFromDevice();
EXPORT_FUNC void pushdelayV1L4I_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L4I_V1L23EFromDevice();
EXPORT_FUNC void pushinSynV1L4I_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L4I_V1L23EFromDevice();
EXPORT_FUNC void pushV1L4I_V1L23EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4I_V1L23EStateFromDevice();
EXPORT_FUNC void pushwV1L4I_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L4I_V1L23IFromDevice();
EXPORT_FUNC void pushactiveV1L4I_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L4I_V1L23IFromDevice();
EXPORT_FUNC void pushdelayV1L4I_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L4I_V1L23IFromDevice();
EXPORT_FUNC void pushinSynV1L4I_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L4I_V1L23IFromDevice();
EXPORT_FUNC void pushV1L4I_V1L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4I_V1L23IStateFromDevice();
EXPORT_FUNC void pushwV1L4I_V1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L4I_V1L4EFromDevice();
EXPORT_FUNC void pushactiveV1L4I_V1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L4I_V1L4EFromDevice();
EXPORT_FUNC void pushdelayV1L4I_V1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L4I_V1L4EFromDevice();
EXPORT_FUNC void pushinSynV1L4I_V1L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L4I_V1L4EFromDevice();
EXPORT_FUNC void pushV1L4I_V1L4EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4I_V1L4EStateFromDevice();
EXPORT_FUNC void pushwV1L4I_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV1L4I_V1L4IFromDevice();
EXPORT_FUNC void pushactiveV1L4I_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV1L4I_V1L4IFromDevice();
EXPORT_FUNC void pushdelayV1L4I_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV1L4I_V1L4IFromDevice();
EXPORT_FUNC void pushinSynV1L4I_V1L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV1L4I_V1L4IFromDevice();
EXPORT_FUNC void pushV1L4I_V1L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV1L4I_V1L4IStateFromDevice();
EXPORT_FUNC void pushwV2L23E_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L23E_V1L23EFromDevice();
EXPORT_FUNC void pushactiveV2L23E_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L23E_V1L23EFromDevice();
EXPORT_FUNC void pushdelayV2L23E_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L23E_V1L23EFromDevice();
EXPORT_FUNC void pushinSynV2L23E_V1L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L23E_V1L23EFromDevice();
EXPORT_FUNC void pushV2L23E_V1L23EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23E_V1L23EStateFromDevice();
EXPORT_FUNC void pushwV2L23E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L23E_V1L23IFromDevice();
EXPORT_FUNC void pushactiveV2L23E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L23E_V1L23IFromDevice();
EXPORT_FUNC void pushdelayV2L23E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L23E_V1L23IFromDevice();
EXPORT_FUNC void pushinSynV2L23E_V1L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L23E_V1L23IFromDevice();
EXPORT_FUNC void pushV2L23E_V1L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23E_V1L23IStateFromDevice();
EXPORT_FUNC void pushwV2L23E_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L23E_V2L23IFromDevice();
EXPORT_FUNC void pushactiveV2L23E_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L23E_V2L23IFromDevice();
EXPORT_FUNC void pushdelayV2L23E_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L23E_V2L23IFromDevice();
EXPORT_FUNC void pushinSynV2L23E_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L23E_V2L23IFromDevice();
EXPORT_FUNC void pushV2L23E_V2L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23E_V2L23IStateFromDevice();
EXPORT_FUNC void pushwV2L23E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L23E_V2L4IFromDevice();
EXPORT_FUNC void pushactiveV2L23E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L23E_V2L4IFromDevice();
EXPORT_FUNC void pushdelayV2L23E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L23E_V2L4IFromDevice();
EXPORT_FUNC void pushinSynV2L23E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L23E_V2L4IFromDevice();
EXPORT_FUNC void pushV2L23E_V2L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23E_V2L4IStateFromDevice();
EXPORT_FUNC void pushwV2L23I_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L23I_V2L23EFromDevice();
EXPORT_FUNC void pushactiveV2L23I_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L23I_V2L23EFromDevice();
EXPORT_FUNC void pushdelayV2L23I_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L23I_V2L23EFromDevice();
EXPORT_FUNC void pushinSynV2L23I_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L23I_V2L23EFromDevice();
EXPORT_FUNC void pushV2L23I_V2L23EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23I_V2L23EStateFromDevice();
EXPORT_FUNC void pushwV2L23I_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L23I_V2L23IFromDevice();
EXPORT_FUNC void pushactiveV2L23I_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L23I_V2L23IFromDevice();
EXPORT_FUNC void pushdelayV2L23I_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L23I_V2L23IFromDevice();
EXPORT_FUNC void pushinSynV2L23I_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L23I_V2L23IFromDevice();
EXPORT_FUNC void pushV2L23I_V2L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L23I_V2L23IStateFromDevice();
EXPORT_FUNC void pushwV2L4E_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L4E_V2L23EFromDevice();
EXPORT_FUNC void pushactiveV2L4E_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L4E_V2L23EFromDevice();
EXPORT_FUNC void pushdelayV2L4E_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L4E_V2L23EFromDevice();
EXPORT_FUNC void pushinSynV2L4E_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L4E_V2L23EFromDevice();
EXPORT_FUNC void pushV2L4E_V2L23EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4E_V2L23EStateFromDevice();
EXPORT_FUNC void pushwV2L4E_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L4E_V2L23IFromDevice();
EXPORT_FUNC void pushactiveV2L4E_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L4E_V2L23IFromDevice();
EXPORT_FUNC void pushdelayV2L4E_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L4E_V2L23IFromDevice();
EXPORT_FUNC void pushinSynV2L4E_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L4E_V2L23IFromDevice();
EXPORT_FUNC void pushV2L4E_V2L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4E_V2L23IStateFromDevice();
EXPORT_FUNC void pushwV2L4E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L4E_V2L4IFromDevice();
EXPORT_FUNC void pushactiveV2L4E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L4E_V2L4IFromDevice();
EXPORT_FUNC void pushdelayV2L4E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L4E_V2L4IFromDevice();
EXPORT_FUNC void pushinSynV2L4E_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L4E_V2L4IFromDevice();
EXPORT_FUNC void pushV2L4E_V2L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4E_V2L4IStateFromDevice();
EXPORT_FUNC void pushwV2L4I_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L4I_V2L23EFromDevice();
EXPORT_FUNC void pushactiveV2L4I_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L4I_V2L23EFromDevice();
EXPORT_FUNC void pushdelayV2L4I_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L4I_V2L23EFromDevice();
EXPORT_FUNC void pushinSynV2L4I_V2L23EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L4I_V2L23EFromDevice();
EXPORT_FUNC void pushV2L4I_V2L23EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4I_V2L23EStateFromDevice();
EXPORT_FUNC void pushwV2L4I_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L4I_V2L23IFromDevice();
EXPORT_FUNC void pushactiveV2L4I_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L4I_V2L23IFromDevice();
EXPORT_FUNC void pushdelayV2L4I_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L4I_V2L23IFromDevice();
EXPORT_FUNC void pushinSynV2L4I_V2L23IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L4I_V2L23IFromDevice();
EXPORT_FUNC void pushV2L4I_V2L23IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4I_V2L23IStateFromDevice();
EXPORT_FUNC void pushwV2L4I_V2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L4I_V2L4EFromDevice();
EXPORT_FUNC void pushactiveV2L4I_V2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L4I_V2L4EFromDevice();
EXPORT_FUNC void pushdelayV2L4I_V2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L4I_V2L4EFromDevice();
EXPORT_FUNC void pushinSynV2L4I_V2L4EToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L4I_V2L4EFromDevice();
EXPORT_FUNC void pushV2L4I_V2L4EStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4I_V2L4EStateFromDevice();
EXPORT_FUNC void pushwV2L4I_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullwV2L4I_V2L4IFromDevice();
EXPORT_FUNC void pushactiveV2L4I_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullactiveV2L4I_V2L4IFromDevice();
EXPORT_FUNC void pushdelayV2L4I_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pulldelayV2L4I_V2L4IFromDevice();
EXPORT_FUNC void pushinSynV2L4I_V2L4IToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullinSynV2L4I_V2L4IFromDevice();
EXPORT_FUNC void pushV2L4I_V2L4IStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void pullV2L4I_V2L4IStateFromDevice();
// Runner functions
EXPORT_FUNC void copyStateToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void copyConnectivityToDevice(bool uninitialisedOnly = false);
EXPORT_FUNC void copyStateFromDevice();
EXPORT_FUNC void copyCurrentSpikesFromDevice();
EXPORT_FUNC void copyCurrentSpikeEventsFromDevice();
EXPORT_FUNC void allocateMem();
EXPORT_FUNC void freeMem();
EXPORT_FUNC size_t getFreeDeviceMemBytes();
EXPORT_FUNC void stepTime();

// Functions generated by backend
EXPORT_FUNC void updateNeurons(float t); 
EXPORT_FUNC void updateSynapses(float t);
EXPORT_FUNC void initialize();
EXPORT_FUNC void initializeSparse();
}  // extern "C"
